### PR TITLE
Backport to C++17

### PR DESCRIPTION
**Pull request by eliemichel**
Do we really need the C++20 requirement? I propose this backport, which also fixes some minor issues and warnings.

### CODE REVIEW

**Comment by fengwang** [comment]
Many thanks for the kind help.

**Comment by eliemichel** [comment]
FYI I am using this for my [WebGPU C++ guide](https://eliemichel.github.io/LearnWebGPU), in particular the [HDR](https://eliemichel.github.io/LearnWebGPU/advanced-techniques/hdr-textures.html) chapter (very very WIP). ;)

(16-bit floats are needed because some GPUs cannot handle filtered sampling of 32-bit float textures)

**Comment by Ghost-LZW** [comment]
Seems like not fully backport to c++17 https://godbolt.org/z/bEzb3afT4

**Comment by eliemichel** [comment]
Mmh indeed, a default value must be provided for all fields in a constexpr constructor, so replacing line 563 fixes the issue:

```
# Replace this:
constexpr inline float16_t() noexcept = default;
# by that:
constexpr inline float16_t() noexcept : data_{ 0 } { }
```

However it means that float16_t will always initialized to 0 even at runtime, which may not be needed by the end user. But I am not sure how to mean "initialize to 0 if compile time otherwise leave uninitialized".

**Pull request merged**
